#imports:
#    - { resource: services/app.yml }
    
application:
    controller_dir: %root_dir%/../
    globals: 
        # Aca definimos las variables globales que queremos tener disponibles en los controladores.
        - request
        
