application:
    controller_dir: %root_dir%
    charset: utf-8
    globals: 
        # Aca definimos las variables globales que queremos tener disponibles en los controladores.
        - request
        
        
twig:
    debug:            %debug%
    strict_variables: %debug%
    globals:
    paths:
        %root_dir%/_views:
        %root_dir%/_views/_shared/templates: templates
        %root_dir%/_views/_shared/partials: partials
        %root_dir%/_views/_shared/macros: macros