services:
    event_dispatcher: 
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container #inyectamos el container
            
    controller_resolver:
        class: Application\Controller\ControllerResolver
        arguments:
            - %controllers_dir%
            - @?logger
