services:
    logger:
        class: Monolog\Logger
        arguments:
            - app_logger

    logger.handler.stream:
        class: Monolog\Handler\StreamHandler
        arguments:
            - %root_dir%/_app/logs/%environment%.log
        tags:
            - { name: logger.handler }
            
    logger.handler.phpfire: 
        class: Monolog\Handler\FirePHPHandler
        tags:
            - { name: logger.handler, debug: true }
            
    logger.handler.chromephp: 
        class: Monolog\Handler\ChromePHPHandler
        tags:
            - { name: logger.handler, debug: true }
            
#    logger.exception_listener:
#        class: Optime\Listener\ExceptionListener
#        properties:
#            logger: @logger
#        tags:
#            - {name: kernel.event_listener, event: app.exception, method: onException}